// This file is generated by Slice Machine. Update with care!

export { default as CategoryWidget } from './CategoryWidget'
export { default as SearchWidget } from './SearchWidget'
export { default as SideWidget } from './SideWidget'
